name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install clean
      run: make

    - name: Make All The Tings
      run: make all
      
    - name: Show file
      run: mek-tcl
